#!/usr/bin/env python3

import os

from labbox import LabBox, Settings
import PyQt5.QtWidgets as QtWidgets
import sys


if __name__ == "__main__":
	app = QtWidgets.QApplication(sys.argv)

	app.setStyle("GTK style")
	if sys.platform != "linux":
		app.setStyle(Settings.defaultStyle)

	ui = LabBox()
	ui.show()

	sys.exit(app.exec_())